---
linters:
  fast: false
  disable-all: true
  enable:
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - golint
    - rowserrcheck
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - maligned
    - depguard
    - misspell
    - lll
    - unparam
    - dogsled
    - nakedret
    - prealloc
    - scopelint
    - gocritic
    - funlen
    - whitespace
    - wsl
    - goprintffuncname
    - gomnd
    # - gochecknoinits
    # - gochecknoglobals
issues:
  exclude-rules:
    - linters:
        - wsl
      text: declarations should never be cuddled
    - linters:
        - golint
      text: should not use dot imports
