---
repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-mod-tidy
- repo: local
  hooks:
    - id: golangci-lint
      entry: make static
      name: golangci-lint
      language: system
