---
repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-mod-tidy
- repo: local
  hooks:
    - id: golangci-lint
      entry: make static
      name: golangci-lint
      language: system
